/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asetperusahaan;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author Windows 8.1
 */
public class fpengadaan extends javax.swing.JFrame {
    int a,b,kali;
    private String[] JudulKolom={"Kode","Tanggal","Nama Barang","Deskripsi","Harga Beli(Rp.)","Jumlah","Total(Rp.)"};
    private int[]LebarKolom ={80,80,120,100,100,100,80,100};
    private String SQL="SELECT * FROM pengadaan";
    /**
     * Creates new form fbarang
     */
    public fpengadaan() {
        initComponents();
        this.setLocationRelativeTo(null);
        new config().setJudulTabel(tabel_pengadaan, JudulKolom);
        new config().tampilTabel(tabel_pengadaan, JudulKolom, SQL);
        new config().setLebarKolomTabel(tabel_pengadaan, LebarKolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        namabarang = new javax.swing.JTextField();
        desk = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        cari = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengadaan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        tot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tgl = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(743, 500));
        setPreferredSize(new java.awt.Dimension(728, 500));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("INVENTORY BARANG");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Inventarisasi Barang (Aset Perusahaan)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 743, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("PENGADAAN BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 112, -1, -1));

        kode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 207, 160, -1));

        namabarang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 160, -1));

        desk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(desk, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 288, 160, -1));

        harga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 319, 131, -1));

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 181, 379, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 411, 80, -1));

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 411, 70, -1));

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 411, 70, -1));

        jLabel4.setText("Kode");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, 20));

        jLabel5.setText("Nama Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, -1, -1));

        jLabel6.setText("Deskripsi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 294, -1, -1));

        jLabel7.setText("Harga");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, -1, -1));

        tabel_pengadaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pengadaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengadaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengadaan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 207, -1, 190));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Pencarian");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 181, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DATA TRANSAKSI");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, 145, 22));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 411, -1, -1));

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 411, -1, -1));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 411, -1, -1));

        jLabel10.setText("Jumlah");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 20));

        jLabel11.setText("Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 17));

        jumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 60, -1));

        tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totActionPerformed(evt);
            }
        });
        getContentPane().add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 132, -1));

        jLabel12.setText("Rp.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 322, -1, -1));

        jLabel13.setText("Rp.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        tgl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yy"))));
        tgl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 234, 160, -1));

        jLabel14.setText("Tanggal");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, -1, 17));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
       String[] Fieldnya={"kode","tanggal","nama_barang","deskripsi","harga","jumlah","total"};
       String[] Valuenya = {kode.getText(),tgl.getText(),namabarang.getText(),desk.getText(),harga.getText(),jumlah.getText(),tot.getText()};
       if ( new config().DuplikasiPrimeryKey("pengadaan","kode",kode.getText()))
           {
            JOptionPane.showMessageDialog(null,"Kode Barang Sudah Ada");
            }else{
                 new config().Simpan("pengadaan",Fieldnya, Valuenya);
                 JOptionPane.showMessageDialog(null,"Data Berhasil di Simpan");
                 new config().setJudulTabel(tabel_pengadaan, JudulKolom);
                 new config().tampilTabel(tabel_pengadaan, JudulKolom, SQL);
                 new config().setLebarKolomTabel(tabel_pengadaan, LebarKolom);
       }
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        String[] Fieldnya={"kode","tanggal","nama_barang","deskripsi","harga","jumlah","total"};
       String[] Valuenya = {kode.getText(),tgl.getText(),namabarang.getText(),desk.getText(),harga.getText(),jumlah.getText(),tot.getText()};
                 new config().Hapus("pengadaan","kode",kode.getText());
                 JOptionPane.showMessageDialog(null,"Data Berhasil di Hapus");;
                 new config().setJudulTabel(tabel_pengadaan, JudulKolom);
                 new config().tampilTabel(tabel_pengadaan, JudulKolom, SQL);
                 new config().setLebarKolomTabel(tabel_pengadaan, LebarKolom);
       
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        String[] Fieldnya={"kode","tanggal","nama_barang","deskripsi","harga","jumlah","total"};
        String[] Valuenya = {kode.getText(),tgl.getText(),namabarang.getText(),desk.getText(),harga.getText(),jumlah.getText(),tot.getText()};
                 new config().Ubah("pengadaan","kode",kode.getText(),Fieldnya, Valuenya);
        JOptionPane.showMessageDialog(null,"Data Berhasil di Ubah");
                 new config().setJudulTabel(tabel_pengadaan, JudulKolom);
                 new config().tampilTabel(tabel_pengadaan, JudulKolom, SQL);
                 new config().setLebarKolomTabel(tabel_pengadaan, LebarKolom);
    }//GEN-LAST:event_ubahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        kode.setText("");
        tgl.setText("");
        namabarang.setText("");
        desk.setText("");
        harga.setText("");
        jumlah.setText("");
        tot.setText("");
    }//GEN-LAST:event_batalActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        new config().tampilLaporan("src/Lap/lap_pengadaan.jrxml","SELECT * FROM pengadaan");
    }//GEN-LAST:event_cetakActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        String SQLCari ="SELECT*FROM pengadaan WHERE kode LIKE'%"+cari.getText()+"%' OR nama_barang LIKE '%"+cari.getText()+"%'";
        new config().setJudulTabel(tabel_pengadaan, JudulKolom);
        new config().tampilTabel(tabel_pengadaan, JudulKolom, SQLCari);
        new config().setLebarKolomTabel(tabel_pengadaan, LebarKolom);
    }//GEN-LAST:event_cariKeyReleased

    private void tabel_pengadaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengadaanMouseClicked
        // TODO add your handling code here:
        int row = tabel_pengadaan.getSelectedRow();
        kode.setText(tabel_pengadaan.getModel().getValueAt(row,0).toString());
        tgl.setText(tabel_pengadaan.getModel().getValueAt(row,1).toString());
        namabarang.setText(tabel_pengadaan.getModel().getValueAt(row,2).toString());
        desk.setText(tabel_pengadaan.getModel().getValueAt(row,3).toString());
        harga.setText(tabel_pengadaan.getModel().getValueAt(row,4).toString());
        jumlah.setText(tabel_pengadaan.getModel().getValueAt(row,5).toString());
        tot.setText(tabel_pengadaan.getModel().getValueAt(row,6).toString());
    }//GEN-LAST:event_tabel_pengadaanMouseClicked

    private void totActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totActionPerformed
        // TODO add your handling code here:
        a = Integer.parseInt(harga.getText());
        b = Integer.parseInt(jumlah.getText());
        kali = a*b;
    
        tot.setText(Integer.toString(kali));
    }//GEN-LAST:event_totActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fpengadaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JTextField cari;
    private javax.swing.JButton cetak;
    private javax.swing.JTextField desk;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField namabarang;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel_pengadaan;
    private javax.swing.JFormattedTextField tgl;
    private javax.swing.JTextField tot;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
